package load.mapper;

import java.util.List;
import load.bean.Shopping;
import load.bean.ShoppingExample;
import org.apache.ibatis.annotations.Param;

public interface ShoppingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    long countByExample(ShoppingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    int deleteByExample(ShoppingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    int insert(Shopping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    int insertSelective(Shopping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    List<Shopping> selectByExample(ShoppingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    Shopping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    int updateByExampleSelective(@Param("record") Shopping record, @Param("example") ShoppingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    int updateByExample(@Param("record") Shopping record, @Param("example") ShoppingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    int updateByPrimaryKeySelective(Shopping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    int updateByPrimaryKey(Shopping record);
}