package load.bean;

import java.util.Date;

public class Communicate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column communicate.id
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column communicate.username
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column communicate.type
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column communicate.text
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column communicate.images
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    private String images;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column communicate.date
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column communicate.id
     *
     * @return the value of communicate.id
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column communicate.id
     *
     * @param id the value for communicate.id
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column communicate.username
     *
     * @return the value of communicate.username
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column communicate.username
     *
     * @param username the value for communicate.username
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column communicate.type
     *
     * @return the value of communicate.type
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column communicate.type
     *
     * @param type the value for communicate.type
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column communicate.text
     *
     * @return the value of communicate.text
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column communicate.text
     *
     * @param text the value for communicate.text
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column communicate.images
     *
     * @return the value of communicate.images
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column communicate.images
     *
     * @param images the value for communicate.images
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column communicate.date
     *
     * @return the value of communicate.date
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column communicate.date
     *
     * @param date the value for communicate.date
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }
}