package load.bean;

import java.util.Date;

public class Goods extends GoodsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.username
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.type
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.detail
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.images
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    private String images;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.date
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.sold
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    private Integer sold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.stock
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    private Integer stock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.username
     *
     * @return the value of goods.username
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.username
     *
     * @param username the value for goods.username
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.type
     *
     * @return the value of goods.type
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.type
     *
     * @param type the value for goods.type
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price
     *
     * @return the value of goods.price
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price
     *
     * @param price the value for goods.price
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.detail
     *
     * @return the value of goods.detail
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.detail
     *
     * @param detail the value for goods.detail
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.images
     *
     * @return the value of goods.images
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.images
     *
     * @param images the value for goods.images
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.date
     *
     * @return the value of goods.date
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.date
     *
     * @param date the value for goods.date
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.sold
     *
     * @return the value of goods.sold
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public Integer getSold() {
        return sold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.sold
     *
     * @param sold the value for goods.sold
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public void setSold(Integer sold) {
        this.sold = sold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.stock
     *
     * @return the value of goods.stock
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.stock
     *
     * @param stock the value for goods.stock
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }
}