package load.bean;

public class GoodsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.version
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    private String version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.version
     *
     * @return the value of goods.version
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.version
     *
     * @param version the value for goods.version
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }
}