package load.bean;

import java.util.Date;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.goodsid
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.buyer
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    private String buyer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.counts
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    private Integer counts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.date
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.status
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.goodsid
     *
     * @return the value of orders.goodsid
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.goodsid
     *
     * @param goodsid the value for orders.goodsid
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.buyer
     *
     * @return the value of orders.buyer
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    public String getBuyer() {
        return buyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.buyer
     *
     * @param buyer the value for orders.buyer
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    public void setBuyer(String buyer) {
        this.buyer = buyer == null ? null : buyer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.counts
     *
     * @return the value of orders.counts
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    public Integer getCounts() {
        return counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.counts
     *
     * @param counts the value for orders.counts
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    public void setCounts(Integer counts) {
        this.counts = counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.date
     *
     * @return the value of orders.date
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.date
     *
     * @param date the value for orders.date
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.status
     *
     * @return the value of orders.status
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.status
     *
     * @param status the value for orders.status
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}