package load.bean;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.goodsid
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.buyer
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    private String buyer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.counts
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    private Integer counts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.date
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.status
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.goodsid
     *
     * @return the value of order.goodsid
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.goodsid
     *
     * @param goodsid the value for order.goodsid
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.buyer
     *
     * @return the value of order.buyer
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public String getBuyer() {
        return buyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.buyer
     *
     * @param buyer the value for order.buyer
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public void setBuyer(String buyer) {
        this.buyer = buyer == null ? null : buyer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.counts
     *
     * @return the value of order.counts
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public Integer getCounts() {
        return counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.counts
     *
     * @param counts the value for order.counts
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public void setCounts(Integer counts) {
        this.counts = counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.date
     *
     * @return the value of order.date
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.date
     *
     * @param date the value for order.date
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.status
     *
     * @return the value of order.status
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.status
     *
     * @param status the value for order.status
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}