package load.bean;

import java.util.Date;

public class Reply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replys.id
     *
     * @mbg.generated Tue May 14 23:05:47 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replys.msgid
     *
     * @mbg.generated Tue May 14 23:05:47 CST 2019
     */
    private Integer msgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replys.type
     *
     * @mbg.generated Tue May 14 23:05:47 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replys.text
     *
     * @mbg.generated Tue May 14 23:05:47 CST 2019
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replys.images
     *
     * @mbg.generated Tue May 14 23:05:47 CST 2019
     */
    private String images;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replys.date
     *
     * @mbg.generated Tue May 14 23:05:47 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replys.rea
     *
     * @mbg.generated Tue May 14 23:05:47 CST 2019
     */
    private String rea;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replys.id
     *
     * @return the value of replys.id
     *
     * @mbg.generated Tue May 14 23:05:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replys.id
     *
     * @param id the value for replys.id
     *
     * @mbg.generated Tue May 14 23:05:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replys.msgid
     *
     * @return the value of replys.msgid
     *
     * @mbg.generated Tue May 14 23:05:47 CST 2019
     */
    public Integer getMsgid() {
        return msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replys.msgid
     *
     * @param msgid the value for replys.msgid
     *
     * @mbg.generated Tue May 14 23:05:47 CST 2019
     */
    public void setMsgid(Integer msgid) {
        this.msgid = msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replys.type
     *
     * @return the value of replys.type
     *
     * @mbg.generated Tue May 14 23:05:47 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replys.type
     *
     * @param type the value for replys.type
     *
     * @mbg.generated Tue May 14 23:05:47 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replys.text
     *
     * @return the value of replys.text
     *
     * @mbg.generated Tue May 14 23:05:47 CST 2019
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replys.text
     *
     * @param text the value for replys.text
     *
     * @mbg.generated Tue May 14 23:05:47 CST 2019
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replys.images
     *
     * @return the value of replys.images
     *
     * @mbg.generated Tue May 14 23:05:47 CST 2019
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replys.images
     *
     * @param images the value for replys.images
     *
     * @mbg.generated Tue May 14 23:05:47 CST 2019
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replys.date
     *
     * @return the value of replys.date
     *
     * @mbg.generated Tue May 14 23:05:47 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replys.date
     *
     * @param date the value for replys.date
     *
     * @mbg.generated Tue May 14 23:05:47 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replys.rea
     *
     * @return the value of replys.rea
     *
     * @mbg.generated Tue May 14 23:05:47 CST 2019
     */
    public String getRea() {
        return rea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replys.rea
     *
     * @param rea the value for replys.rea
     *
     * @mbg.generated Tue May 14 23:05:47 CST 2019
     */
    public void setRea(String rea) {
        this.rea = rea == null ? null : rea.trim();
    }
}