package load.bean;

public class Settings {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.id
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.key
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.value
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    private Integer value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.id
     *
     * @return the value of settings.id
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.id
     *
     * @param id the value for settings.id
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.key
     *
     * @return the value of settings.key
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.key
     *
     * @param key the value for settings.key
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.value
     *
     * @return the value of settings.value
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.value
     *
     * @param value the value for settings.value
     *
     * @mbg.generated Fri May 10 17:34:26 CST 2019
     */
    public void setValue(Integer value) {
        this.value = value;
    }
}