package load.bean;

import java.util.Date;

public class Shopping {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping.id
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping.goodsid
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping.buyer
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    private String buyer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping.counts
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    private Integer counts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping.date
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping.id
     *
     * @return the value of shopping.id
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping.id
     *
     * @param id the value for shopping.id
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping.goodsid
     *
     * @return the value of shopping.goodsid
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping.goodsid
     *
     * @param goodsid the value for shopping.goodsid
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping.buyer
     *
     * @return the value of shopping.buyer
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    public String getBuyer() {
        return buyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping.buyer
     *
     * @param buyer the value for shopping.buyer
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    public void setBuyer(String buyer) {
        this.buyer = buyer == null ? null : buyer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping.counts
     *
     * @return the value of shopping.counts
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    public Integer getCounts() {
        return counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping.counts
     *
     * @param counts the value for shopping.counts
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    public void setCounts(Integer counts) {
        this.counts = counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping.date
     *
     * @return the value of shopping.date
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping.date
     *
     * @param date the value for shopping.date
     *
     * @mbg.generated Tue May 14 22:10:49 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }
}